package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/urfave/cli/v3"
	"gopkg.in/yaml.v3"
)

// container_agentprecommit.go emits the agent-only commit-msg pre-commit config
// (ward#139): it enables the agentic-os suite. See docs/agent-precommit.md.

// agentPreCommitHooks are the agentic-os commit-msg-stage hook ids the agent
// suite enables - the two checks ward#139 calls for.
var agentPreCommitHooks = []string{"closes-issue", "conventional-commit"}

// agenticOSRepoMarker identifies the agentic-os repo entry in a pre-commit
// config (the repo that ships the commit-msg suite).
const agenticOSRepoMarker = "agentic-os"

// preCommitConfigDoc is the minimal shape we read from a .pre-commit-config.yaml:
// each repo entry's source URL and pinned rev.
type preCommitConfigDoc struct {
	Repos []struct {
		Repo string `yaml:"repo"`
		Rev  string `yaml:"rev"`
	} `yaml:"repos"`
}

// agentPreCommitConfig returns an agent-only config enabling the agentic-os
// commit-msg suite at the same rev the repo's config pins. See docs/agent-precommit.md.
func agentPreCommitConfig(repoConfig []byte) ([]byte, error) {
	var doc preCommitConfigDoc
	if err := yaml.Unmarshal(repoConfig, &doc); err != nil {
		return nil, fmt.Errorf("parse pre-commit config: %w", err)
	}
	repoURL, rev := "", ""
	for _, r := range doc.Repos {
		if strings.Contains(r.Repo, agenticOSRepoMarker) {
			repoURL, rev = r.Repo, strings.TrimSpace(r.Rev)
			break
		}
	}
	if repoURL == "" {
		return nil, fmt.Errorf("no agentic-os repo entry in pre-commit config; cannot enable the agent commit suite")
	}
	if rev == "" {
		return nil, fmt.Errorf("agentic-os repo entry %q has no pinned rev; cannot enable the agent commit suite", repoURL)
	}

	var b strings.Builder
	b.WriteString("# Generated by `ward container agent-precommit-config` (ward#139).\n")
	b.WriteString("# Agent-only commit-msg suite, installed in headless/task runs; do not commit.\n")
	b.WriteString("repos:\n")
	fmt.Fprintf(&b, "  - repo: %s\n", repoURL)
	fmt.Fprintf(&b, "    rev: %s\n", rev)
	b.WriteString("    hooks:\n")
	for _, id := range agentPreCommitHooks {
		fmt.Fprintf(&b, "      - id: %s\n", id)
	}
	return []byte(b.String()), nil
}

// containerAgentPreCommitCommand returns `ward container agent-precommit-config`:
// the entrypoint-internal generator for the agent-only commit-msg suite.
func containerAgentPreCommitCommand() *cli.Command {
	return &cli.Command{
		Name:  "agent-precommit-config",
		Usage: "Emit the agent-only commit-msg pre-commit config (closes-issue + conventional-commit at the repo's pinned agentic-os rev). Entrypoint-internal (ward#139).",
		Flags: []cli.Flag{
			&cli.StringFlag{Name: "config", Usage: "path to the repo .pre-commit-config.yaml (default: ./.pre-commit-config.yaml)"},
		},
		Action: func(_ context.Context, c *cli.Command) error {
			path := c.String("config")
			if path == "" {
				path = ".pre-commit-config.yaml"
			}
			data, err := os.ReadFile(path) // #nosec G304 -- caller-controlled config path
			if err != nil {
				return fmt.Errorf("ward container agent-precommit-config: read %s: %w", path, err)
			}
			out, err := agentPreCommitConfig(data)
			if err != nil {
				return fmt.Errorf("ward container agent-precommit-config: %w", err)
			}
			_, err = os.Stdout.Write(out)
			return err
		},
	}
}
